### PR TITLE
Fix generator phpstan regexp

### PR DESCRIPTION
**Pull request by szepeviktor**
a lot of _ignored by mistake_ errors popped out
https://travis-ci.org/thecodingmachine/safe/jobs/625615584#L298

### CODE REVIEW

**Comment by Kharhamel** [comment]
I am not sure I understand. Do you have theses errors after editing the phpstan.neon or before?

**Comment by szepeviktor** [comment]
After *fixing* the broken regexp-s.
It covered all string related type errors: the `|` sign was not escapes.

**Comment by szepeviktor** [comment]
Now we face all errors introduced while using broken regexp-s.

**Comment by Kharhamel** [comment]
ok I get it, you are right the regexp are false and cause the phpstan to ignore too many errors. I am going to fix them.

**Comment by Kharhamel** [comment]
Done: #168

**Comment by Kharhamel** [comment]
This is merged. Thank you for pointing this out.

**Pull request closed without merging**
