### PR TITLE
Enhancement: Install root dependencies using GitHub Actions

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] adds a very small workflow installing root dependencies with `composer` using GitHub Actions

💁‍♂ This could be a small start, and we could switch over more steps as seen in #191.

### CODE REVIEW

**Comment by Kharhamel** [comment]
Sorry, I didn't reply sooner, I had quite a lot of work lately. Thanks for this PR. I am going to test this on my own fork before merging, I will try to do this this week.

**Comment by localheinz** [comment]
@Kharhamel 

You can take a look at this workflow in action at https://github.com/localheinz/safe/pull/1.

**Comment by Kharhamel** [comment]
Ok this looks good, thank you very much

**Comment by localheinz** [comment]
Thank you, @Kharhamel!

**Pull request merged**
