### PR TITLE
enable strict_types in generator

### PR DESCRIPTION
**Pull request by shish**
(Continuing with pulling the changes from shish/safe into tcm/safe in small hopefully easy-to-review chunks)

### CODE REVIEW

**Comment by staabm** [comment]
awesome, thanks for all this.

fyi, I would wait before merging new PRs, until [the generator is fixed](https://github.com/thecodingmachine/safe/pull/478#issuecomment-2511469302)

**Comment by shish** [comment]
The generator is already working in my branch - these PRs are me trying to get us in-sync one small step at a time :)

**Comment by staabm** [comment]
> The generator is already working in my branch - these PRs are me trying to get us in-sync one small step at a time :)

I see. do you think its possible to work on PRs which get the generator running first?

**Comment by shish** [comment]
Technically anything is possible with enough effort - but those changes are built on top of these ones, and I worry that trying to re-order the commits would cause more merge-conflicts with more potential to mess things up ^^;;

**Comment by staabm** [comment]
I see. please leave a hint in the PRs so we can be sure they get merged in the correct order.

**Pull request merged**
