### PR TITLE
more strict php requirement

### PR DESCRIPTION
**Pull request by dbrekelmans**

### CODE REVIEW

**Comment by dbrekelmans** [comment]
Hi @fox91, following your PR with submodules (https://github.com/thecodingmachine/safe/pull/292), I'm targeting the `1.x` branch, but for some reason the github actions are detecting changes in the generated files. I'm not sure how this is possible, do you perhaps have any idea?

**Comment by fox91** [comment]
@dbrekelmans try using this on actions:
```yaml
- name: Checkout repository and submodules
  uses: actions/checkout@v2
  with:
    submodules: recursive
```

Instead of "Checkout" and "Check out submodules"

**Comment by Kharhamel** [comment]
The CI workflow use a cache (https://github.com/actions/cache) which may be reused between master and 1.x. It would probably be easier to just remove the cache on 1.x

**Comment by fox91** [comment]
Hi @Kharhamel, any news about the solutions that I've suggested [here](https://github.com/thecodingmachine/safe/pull/314#issuecomment-1005785148)?

**Comment by staabm** [comment]
I think this one is obsolete

**Pull request closed without merging**
