### PR TITLE
added test to reproduce issue with array_multisort

### PR DESCRIPTION
**Pull request by dmecke**
reproduces #104

### CODE REVIEW

**Comment by moufmouf** [comment]
Excellent. Thanks a lot for the test!

**Comment by moufmouf** [comment]
Ok, I've tried to correct this and it turns out it is actually impossible :(

I changed the signature of the Safe\array_multisort function to be:

```php
function array_multisort(array &$array1, &$array1_sort_order = SORT_ASC, &$array1_sort_flags = SORT_REGULAR, ...$params): void
```

But now, when I run your unit test, I get this:

```
array_multisort($sort, SORT_ASC, $integersSafe);
// Error: Cannot pass parameter 2 by reference
```

This is because in "userland" PHP, you cannot pass a constant in an argument that expects a reference.

The 2nd argument of `array_multisort` function can be either an int, OR an array passed by reference and there is no way to reproduce that in userland.

Hence, we are screwed :(.

The only solution I see so far is to remove `array_multisort` altogether from Safe. Which means introducing a BC break... :rage:

**Comment by dmecke** [comment]
`array_multisort` has indeed a terrible signature. I don't have a solution neither, but maybe an alternative to removing it altogether would be to throw an exception when an array is passed in and keep the current implementation. That would be a bc break as well, but in fact it is broken now when passing an array, so a bc break with an exception is imho still better that a misbehaviour without notice.

**Comment by k00ni** [comment]
I just stumbled over this project and checked this pull request. Please correct me if am wrong, but why not left the type for parameter `$array1_sort_order` and instead check it inside the function?

Based on the documentation the second parameter is **by value** anyway:

```
array_multisort (
    array &$array1 
    [, mixed $array1_sort_order = SORT_ASC 
        [, mixed $array1_sort_flags = SORT_REGULAR 
            [, mixed $... ]]] 
) : bool
```

Source: https://www.php.net/manual/en/function.array-multisort.php

**Comment by Kharhamel** [comment]
array_multisort will be removed in version 1.0.0. #167

**Pull request closed without merging**
