### PR TITLE
Fix: Regenerate files

### LINKED ISSUE #187: Warning: ldap_bind() expects at most 3 parameters, 4 given
When using `thecodingmachine/safe:1.0.2` on PHP 7.3.11, we have observed the following warning:

> Warning: ldap_bind() expects at most 3 parameters, 4 given

When looking at

* https://github.com/php/php-src/blob/php-7.3.11/ext/ldap/ldap.c#L1142-L1194
* https://github.com/php/php-src/blob/php-7.4.1/ext/ldap/ldap.c#L1117-L1169

it's not apparent that `ldap_bind()` accepts 4 arguments.

In contrast, the wrapping function `Safe\ldap_bind()` accepts and invokes `ldap_bind()` with 4 arguments :

* https://github.com/thecodingmachine/safe/blob/v1.0.2/generated/ldap.php#L90-L97

The documentation, from which the code is generated, states that `ldap_bind()` accepts 4 arguments:

* https://www.php.net/manual/en/function.ldap-bind.php

Perhaps there is something wrong with the documentation?

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] regenerates all files

Fixes #187.

💁‍♂ For reference, see https://github.com/php/doc-en/pull/20.

### CODE REVIEW

**Comment by Kharhamel** [comment]
Thanks for the pr. Sorry i didn't see your issue, I rarely check github during the week end

**Comment by localheinz** [comment]
Thank you, @Kharhamel and @OskarStark!

**Comment by OskarStark** [comment]
Thank you @Kharhamel could you please create a new release?

**Comment by Kharhamel** [comment]
Oh yeah I forgot sorry

**Pull request merged**
