### PR TITLE
Run CI fo PHP 7.4

### PR DESCRIPTION
**Pull request by moufmouf**
This is a continuation of #205

### CODE REVIEW

**Comment by localheinz** [comment]
Build fails because of #209.

**Comment by localheinz** [comment]
@moufmouf 

Why not merge #209 first?

We don’t need to do all the work twice, do we?

**Comment by moufmouf** [comment]
@localheinz You are perfectly right. I was attempting to bring a part of #209 in this PR while keeping Rector files for 0.5 and 0.6. But it seems harder that I expected. I'll revert the commits on this branch.

**Comment by localheinz** [comment]
@moufmouf 

I think we can ditch any effort to keep support for unsupported `rector/rector` versions.

**Comment by localheinz** [comment]
@moufmouf 

What do you think about 

- resetting hard to 884b515
- rebasing on top of `master`

?

**Pull request closed without merging**
