### PR TITLE
bring in curl handles

### PR DESCRIPTION
**Pull request by mmoll**
see https://php.watch/versions/8.0/resource-CurlHandle

### CODE REVIEW

**Comment by mmoll** [comment]
Not sure if this is correct, but I saw errors like 
```
[...]
  90     Parameter #1 $handle of function Safe\curl_setopt expects resource, CurlHandle given.   
  92     Parameter #1 $handle of function Safe\curl_exec expects resource, CurlHandle given.     
  93     Parameter #1 $handle of function Safe\curl_getinfo expects resource, CurlHandle given.
```
also with #315.

**Comment by mmoll** [comment]
now what? 🤔

**Comment by dbrekelmans** [comment]
Hi @mmoll, sorry I missed this PR.

Thanks for the effort so far.

The correct way to fix this, is to add these functions to `generator/src/PhpStanFunctions/CustomPhpStanFunctionMap.php` as was done in #315.
`generated/curl.php` is, as the directory suggest, generated and should not be edited manually.
This allows us to automatically update the generated files when the php docs are updated instead of manually updating all the changed functions on every php release.

If you could update the PR and make sure the build is green, I will gladly merge this!

**Comment by mmoll** [comment]
Thanks @dbrekelmans, I hope it's coming back green now. 💚

**Comment by mmoll** [comment]
should be fixed now

**Comment by dbrekelmans** [comment]
Thanks @mmoll!

**Pull request merged**
