### PR TITLE
Hard-coding coveralls secret

### PR DESCRIPTION
**Pull request by moufmouf**
Putting the Coveralls secret in clear text (to be able to have coveralls info in forks)
This means anyone can push information in Safe coveralls. We are ok with that "risk"

### CODE REVIEW

**Comment by moufmouf** [comment]
Indeed. I would have expected a red flag here. I'm not sure what went wrong.
I'll try with this Github action instead: https://github.com/marketplace/actions/coveralls-github-action

**Comment by moufmouf** [comment]
Apparently the Github action expects a file in LCOV format that cannot be provided by PHPUnit :(

```
0s
  '          <metrics complexity="62" methods="11" coveredmethods="6" conditionals="0" coveredconditionals="0" statements="120" coveredstatements="97" elements="131" coveredelements="103"/>\n' +
Run coverallsapp/github-action@master
Using lcov file: generator/build/logs/clover.xml
[error] "2020-02-24T13:18:52.864Z"  'error from lcovParse: ' 'Failed to parse string'
[error] "2020-02-24T13:18:52.865Z"  'input: ' '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<coverage generated="1582550251">\n' +
  '  <project timestamp="1582550251">\n' +
  '    <package name="Safe">\n' +
  '      <file name="/home/runner/work/safe/safe/generator/src/ComposerJsonEditor.php">\n' +
```

**Comment by moufmouf** [comment]
Ok. We are missing support from Github Actions from PHP-Coveralls package.

PR is pending here: https://github.com/php-coveralls/php-coveralls/pull/275

As soon as this is merged, I think we can try again and finally get code coverage is forks too.

**Comment by simPod** [comment]
You should use github token instead

I implemented it here https://github.com/webonyx/graphql-php/blob/master/.github/workflows/ci-build.yml#L159

**Comment by localheinz** [comment]
Why not use https://codecov.io instead?

With codecov, token-less uploads work fine on GitHub Actions.

**Comment by Kharhamel** [comment]
Not needed anymore since we use codecov, thanks for the tip @localheinz

**Comment by simPod** [comment]
token is not issue with coveralls. Though the coveralls php repo is dead so covecov is definitely the better alternative.

**Pull request closed without merging**
