### PR TITLE
Fix: Drop support for unsupported versions of rector/rector

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] drops support for outdated versions of `rector/rector`
* [x] regenerates files

Replaces #204.

💁‍♂ For reference, see https://github.com/rectorphp/rector/issues/2973#issuecomment-593002504.

### CODE REVIEW

**Comment by moufmouf** [comment]
I'm just starting to realize... Rector 0.6 does not work with any version of PHP anymore, it is completely broken, isn't it?
Because of some dependency issue with a Simplify package?

**Comment by moufmouf** [comment]
I'm a bit reluctant to remove support for old versions of Rector (we already did that for Rector 0.3 and it caused problems for some users). But of course, if the package is broken for everybody, it shouldn't be a problem.
@Kharhamel what do you think about this?

**Comment by localheinz** [comment]
@moufmouf 

> I'm a bit reluctant to remove support for old versions of Rector (we already did that for Rector 0.3 and it caused problems for some users). But of course, if the package is broken for everybody, it shouldn't be a problem.

I wouldn't worry about it:

- `rector/rector` is not a direct dependency of `thecodingmachine/safe`
- if anyone wants to use `thecodingmachine/safe` and at the same time use `rector/rector` to modify their code, they will be able to find a way, for example: use a dedicated `composer.json` and a corresponding step that installs the required version of `rector/rector`, and then runs it

**Comment by localheinz** [comment]
Thank you, @Kharhamel and @moufmouf!

**Pull request merged**
