### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by szepeviktor**
Using https://github.com/crate-ci/typos
Something like #416 on a bigger scale.

This is all I can offer. Please make changes yourself.
If you wish I could revert `generated/*` files so you can work easier.

### CODE REVIEW

**Comment by szepeviktor** [comment]
💡 There is a new file called `rnp.php`

**Comment by staabm** [comment]
hey.

I am one of the new maintainers which recently got invited to revive this repo.

Thanks for the time you invested in this PR.
In the meantime we merged other PRs which results in conflicts here.

Feel free to contribute a similar PR in the future, after we worked thru the merge queue and got a PHP 8.1+ release out the door

thanks again

**Comment by szepeviktor** [comment]
@staabm Would you welcome a PR fixing misspellings?

**Comment by staabm** [comment]
> Would you welcome a PR fixing misspellings?

yes, but not now. please wait until we worked out a PHP 8.1 compatible release

**Comment by szepeviktor** [comment]
Is it time to reopen this PR?

**Comment by shish** [comment]
I'd be happy for a PR with typo-fixing, though so much has changed that it might be worth starting from scratch rather than trying to rebase and deal with merge conflicts :sweat_smile:

**Pull request closed without merging**
