### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by simoheinonen**

### CODE REVIEW

**Comment by peter279k** [comment]
After checking Travis CI build log, it seems that's broken.

And the message is here: ` The process "vendor/bin/phpcbf" exceeded the timeout of 60 seconds.`
The work `cd generator && ./safe.php generate && cd ..` execution time is so long that the Travis CI kill that.

I think it should set the `travis_wait ` before this command to complete this work successfully 👍 .

**Comment by moufmouf** [comment]
Ok, timeout if fixed in #28 .
I'm merging this.

Thanks @simoheinonen  and thanks @peter279k for the analysis.

**Comment by peter279k** [comment]
Well, the issue is still existed.

Please check the [Travis CI builld log](https://travis-ci.org/thecodingmachine/safe/jobs/428522877).

**Comment by moufmouf** [comment]
Ho, these are 2 separate issues.

In the previous log, the issue was about the CS fixer taking too much time (it's a process I call from the PHP, and I did put a longer timeout in the PHP code). It was PHP that was timing out, not travis.

But right now, there is another issue. This time, it is indeed Travis that is timing out. This is because the SVN for the PHP documentation has been down for about one hour. There is nothing I can do here but to wait that the SVN is put up again... :(

**Pull request merged**
