### PR TITLE
Enhancement: Switch to using GitHub Actions

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] switches from using Travis CI to GitHub Actions

### CODE REVIEW

**Comment by localheinz** [comment]
@Kharhamel 

Would there be interest in switching over?

**Comment by Kharhamel** [comment]
Yes @moufmouf already talked about this, I wanted to try it but didn't find the time.
Thank you for that draft. Did you test it?

**Comment by Kharhamel** [comment]
Looking at your branch, it looks like you broke the link for the continuous integration in the README

**Comment by localheinz** [comment]
@Kharhamel 

It looks like that because there currently isn't a workflow configured.

If you prefer, we can start small and switch over step by step!

**Comment by Kharhamel** [comment]
see #195

I switch everything to github actions but there is still some issues with svn

**Comment by Kharhamel** [comment]
Also the code coverage doesn't work anymore. The build directory isn't generated. Any idea why?

**Pull request closed without merging**
