### PR TITLE
Replace PSR-4 with classmap autoloader

### LINKED ISSUE #253: Cannot redeclare Safe\array_combine()
Hi there, congrats on the project, I just discovered it and I think is great.

Now, I've tried to add it to one of my libraries and now when I run phpstan (with our without the rule) I get the following error:
```
PHP Fatal error:  Cannot redeclare Safe\array_combine() (previously declared in /home/user/project/vendor/thecodingmachine/safe/generated/array.php:20) in /home/user/project/vendor/thecodingmachine/safe/generated/array.php on line 20

Fatal error: Cannot redeclare Safe\array_combine() (previously declared in /home/user/project/vendor/thecodingmachine/safe/generated/array.php:20) in /home/user/project/vendor/thecodingmachine/safe/generated/array.php on line 20

In array.php line 20:
                                                                                                                                                              
  Cannot redeclare Safe\array_combine() (previously declared in /home/user/project/vendor/thecodingmachine/safe/generated/array.php:20)  
                                                                                                                                                              
```

The file obviously don't have the function declared twice and I'm completely lost as for where it could be coming from. Any ideas? I'm on 1.3.3.

Thanks!

### PR DESCRIPTION
**Pull request by j3j5**
I am once again ~asking for your support~ trying to fix #253. 

I think this is the best approach (as discussed on [the phpdocparser issue](https://github.com/phpstan/phpdoc-parser/issues/117) ) and it's also much less disruptive than the renaming of all files done in #338.

I've tested the code with [this repo](https://github.com/j3j5/phpstan-larastan-bug), but please, test it yourselves to make sure I don't break anything else again :stuck_out_tongue: 

Hope this is the good one!

### CODE REVIEW

**Comment by Kharhamel** [comment]
This looks really easy. I need to think about how to test this on a bigger scale. I will probably create a beta for this but this means i need to merge this into master.

**Comment by j3j5** [comment]
Yeah, please double check that I didn't miss any class. The only downside is that if a new class is ever added that doesn't fall in the folders (new exceptions will be fine), it'll need to be added manually. I don't think there will be another case like Datetime in this library, but something to be aware of.

**Comment by szepeviktor** [comment]
@j3j5 I think #348 is the ultimate solution.

**Comment by j3j5** [comment]
As I mentioned on previous attempts, I don't mind which approach we use, I just want to get rid of the error so whatever is easier/better for the actual maintainers :)

**Comment by Kharhamel** [comment]
@szepeviktor didn't propose his pull request yet, so I am going to merge this for now and create a beta to test it. Is it ok with you @j3j5?

**Comment by j3j5** [comment]
Yeah, I mean, it should fix the problem for now (hopefully) and later we can go with the "final solution" if y'all like it better.

**Pull request merged**
