### PR TITLE
Enhancement: Use actions/checkout to check out documentation

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] uses `actions/checkout` to check out the documentation

### CODE REVIEW

**Comment by Kharhamel** [comment]
What does this change compared to the previous version?

**Comment by localheinz** [comment]
@Kharhamel 

It's faster, and it does not depend on `update.sh`.

**Comment by localheinz** [comment]
Build failure is fixed in #211.

**Comment by localheinz** [comment]
Thank you, @Kharhamel and @OskarStark!

**Pull request merged**
